### ISSUE TITLE
Swipe direction in RTL is wrong

### ISSUE THREAD

**Issue by farhad2161** [googlesamples/android-SlidingTabsBasic#1]
Swipe direction in right to left language is wrong.
Add following code to MainActivity onCreate 

```
    Locale locale = new Locale("fa");
    Locale.setDefault(locale);
    Configuration config = new Configuration();
    config.locale = locale;
    Resources resources = getBaseContext().getResources();
    resources.updateConfiguration(config, resources.getDisplayMetrics());
```

And also add  android:supportsRtl="true"  to application in AndroidManifest.xml file.

Now when you start the app, you should swipe RIGHT  in order to go next tab but it is not possible and it will work in wrong direction.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
