### ISSUE TITLE
cant find the function  setDistributeEvenly in SlidingTabLayout.java

### ISSUE THREAD

**Issue by ameenmaheen** [googlesamples/android-SlidingTabsBasic#2]
i cant find the function  setDistributeEvenly in SlidingTabLayout.java which makes the tabs even

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
