### ISSUE TITLE
RTL problem when too many tabs available in api 17 and 18

### ISSUE THREAD

**Issue by hamidrezabstn** [googlesamples/android-SlidingTabsBasic#5]
hi 

please open sample app in emulator for api 17 or 18 in rtl direction! all the tabs go off screen! :((

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
