### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by cloned2k16** [googlesamples/android-SlidingTabsBasic#7]
* What went wrong:
A problem occurred configuring project ':Application'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 28s

**Comment by rayworks** [comment]
@cloned2k16 
I came across the same issue, had fixed it by upgrading the gradle tool version as below: 
`classpath 'com.android.tools.build:gradle:3.2.1'`

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
